name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: vinted-bot:latest
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Save and transfer image
        run: |
          docker save vinted-bot:latest > image.tar
          scp image.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/debian/vinted-discord-bot-2/

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/debian/vinted-discord-bot-2
            docker-compose down
            docker load < image.tar
            rm image.tar
            docker-compose up -d
